title: Project Portfolio
logo: https://media.licdn.com/dms/image/D4E03AQHaY1NgQoMa4g/profile-displayphoto-shrink_800_800/0/1714929633772?e=1725494400&v=beta&t=_LRTdO4cR4SiK-I4g4NOkZ8DS95ZHIkN06Jx6Nv9RvU
description: Welcome to my project portfolio! Here you will find a collection of my work showcasing my skills in data analysis, and science. Each project reflects my commitment to solving complex problems with efficient and scalable solutions.
theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
